services:
  microservice:
      container_name: microservice
      image: microservice
      build:
        context: ./web
        dockerfile: microservice.dockerfile
      ports:
        - "9010:9010"
      networks:
        - redis-net
      depends_on:
        - redis
      restart: always

  redis:
      image: redis
      container_name: redis
      restart: unless-stopped
      volumes:
          - ./redis/data:/data
          - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      networks:
        - redis-net
      expose:
          - 6379
      command: redis-server /usr/local/etc/redis/redis.conf

networks:
  redis-net:
    driver: bridge
